#!/bin/bash

export COMPOSE_FILE=docker-compose.yml
export ENV_FILE=local_env

if [[ "$1" = "up" ]]; then
    if [ "$2" = "debug" ]; then
        echo "Starting Application in DEBUG MODE...";
        docker-compose -f $COMPOSE_FILE --env-file ${ENV_FILE} up api.debug db
    else
        echo "Starting Application...";
        docker-compose -f $COMPOSE_FILE --env-file ${ENV_FILE} up
    fi
fi

if [ "$1" = "run" ]; then
    if [ "$2" = "build" ]; then
        if [ "$3" = "debugger" ]; then
            echo "Building Debugger...";
            docker-compose -f $COMPOSE_FILE --env-file ${ENV_FILE} build api.debug
        else
            echo "Building Application...";
            docker-compose -f $COMPOSE_FILE --env-file ${ENV_FILE} build api
        fi
    fi
fi

if [[ "$1" == 'gendoc' ]]; then
  cd src/haste/infra/driver
  bee generate docs
#   rm -rf _swagger
#   mkdir _swagger
#   mv swagger/swagger.json _swagger/swagger-olympus.json
#   rm -rf swagger
fi