#!/bin/bash

export COMPOSE_FILE=docker-compose.yml
export ENV_FILE=.env
export PROD_ENV_FILE=.env.prod

#  later this prod env file need to be removed in code base and directly injected at time of containerisation in server 
if [[ "$1" = "up" ]]; then
    if [ "$(docker-compose ps -q)" ]; then
            echo "Stopping and removing existing containers..."
            docker-compose down
    else
            echo "No containers are running."
    fi
    if [ "$2" = "debug" ]; then
        echo "Starting Application in DEBUG MODE...";
        docker-compose -f $COMPOSE_FILE --env-file ${ENV_FILE} up api.debug db
    elif [ "$2" = "prod" ]; then
        echo "Starting Application in PRODUCTION MODE...";
        # later remove this prod env file and this shuld be injected to containers in the instace level without any prod env files in code base
        docker-compose -f docker-compose.prod.yml --env-file ${PROD_ENV_FILE} build api
        docker-compose -f docker-compose.prod.yml --env-file ${PROD_ENV_FILE} up api db
    else
        echo "Starting Application...";
        docker-compose -f $COMPOSE_FILE --env-file ${ENV_FILE} up
    fi
fi

if [ "$1" = "run" ]; then
    if [ "$2" = "build" ]; then
        if [ "$3" = "debugger" ]; then
            echo "Building Debugger..";
            docker-compose -f $COMPOSE_FILE --env-file ${ENV_FILE} build api.debug
        else
            echo "Building Application...";
            docker-compose -f $COMPOSE_FILE --env-file ${ENV_FILE} build api
        fi
    fi
fi

if [[ "$1" == 'gendoc' ]]; then
  cd src/haste/infra/driver
  bee generate docs
#   rm -rf _swagger
#   mkdir _swagger
#   mv swagger/swagger.json _swagger/swagger-olympus.json
#   rm -rf swagger
fi