version: '3.8'

services:
  api:
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - NODE_ENV=production
    restart: on-failure
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080" 
    networks:
      - network_backend
      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - saha_prod:/var/lib/postgresql/data 
    ports:
      - "5432:5432"    
    networks:
      - network_backend

volumes:
  saha_prod:  

networks:
  network_backend:
