version: '3.8'

services:
  # web:
  #   depends_on:
  #     - api
  #     - db
  #   build:
  #     context: ./web
  #   ports:
  #     - "3000:3000" 
  #   volumes:
  #     - ./web:/app
  #   networks:
  #     - network-backend 

  api:
    depends_on:
      - db
    build:
      context: ./api
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    ports:
      - "8080:8080" 
    volumes:
      - ./api:/app
    networks:
      - network_backend
      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - saha_local:/var/lib/postgresql/data 
    ports:
      - "5432:5432"    
    networks:
      - network_backend

volumes:
  saha_local:  

networks:
  network_backend:
