version: '3.8'

services:
  # web:
  #   depends_on:
  #     - api
  #     - db
  #   build:
  #     context: ./web
  #   ports:
  #     - "3000:3000" 
  #   volumes:
  #     - ./web:/app
  #   networks:
  #     - network-backend 

  api:
    depends_on:
      - db
    environment:
      - DB_HOST=db
    build:
      context: ./api
    # env_file:
    #   - ./api/.env
    ports:
      - "8080:8080" 
    volumes:
      - ./api:/app
    networks:
      - network_backend
      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - saha_local:/var/lib/postgresql/data 
    ports:
      - "5432:5432"    
    networks:
      - network_backend

volumes:
  saha_local:  

networks:
  network_backend:
