version: '3.8'

services:
  api:
    depends_on:
      - db
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080" 
    networks:
      - network_backend
      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - saha_prod:/var/lib/postgresql/data 
    ports:
      - "5432:5432"    
    networks:
      - network_backend

volumes:
  saha_prod:  

networks:
  network_backend:
