name: Deploy to EC2

on:
  pull_request:
    types: [closed]  # This triggers on PR merge

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -rv -o StrictHostKeyChecking=no * ec2-user@3.12.104.221:./app

      - name: SSH to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.12.104.221 << 'EOF'
            cd ./app
            ./dev-env up prod
          EOF
